import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Search from "./components/search";
// import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Acme Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {


  // const[serched , setSerched] = useState("")
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
              <header className="border-b-[0.2px] border-gray-500 bg-black p-4">
        <nav className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-6">
            <Link href="/" className="flex items-center gap-2 font-bold text-white">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg border border-gray-200 bg-gray-100 p-2">
                <svg viewBox="0 0 24 24" fill="black" className="h-4 w-4">
                  <path d="M3.5 18.5 11.1 5.2a1 1 0 0 1 1.8 0l2.2 3.9-5.4 9.4H3.5Z" />
                  <path d="m13.9 12.4 3.5 6.1h-7l3.5-6.1Z" />
                </svg>
              </div>
              <span className="text-sm uppercase tracking-widest">ACME STORE</span>
            </Link>

            <div className="flex items-center gap-4 text-sm font-medium text-gray-400">
              <Link href="/bags" className="hover:border-b hover:text-white">Bags</Link>
              <Link href="/shoes" className="hover:border-b hover:text-white">Shoes</Link>
              <Link href="/shopAll" className="hover:border-b hover:text-white">ShopAll</Link>
              <Link href="/sunglasses" className="hover:border-b hover:text-white">Sunglasses</Link>
            </div>
          </div>


           < Search />
         
          

          <Link
            href="/cart"
            aria-label="Shopping cart"
            className="relative flex h-11 w-11 items-center justify-center rounded-md border border-gray-500 text-white"
          >
            <svg
              aria-hidden="true"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="h-4 w-4"
            >
              <circle cx="8" cy="21" r="1" />
              <circle cx="19" cy="21" r="1" />
              <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
            </svg>
            <span className="absolute right-1 top-1 flex h-4 w-4 items-center justify-center rounded-full bg-blue-600 text-[10px] font-bold text-white">
              0
            </span>
          </Link>
        </nav>
      </header>
        
        
        
        
        {children}
        
        


        <footer className="flex gap-4 ">


          <Link href="/" className="flex items-center gap-2 font-bold text-white ml-[30px] mt-[30px]">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg border border-gray-200 bg-gray-100 p-2">
                <svg viewBox="0 0 24 24" fill="black" className="h-4 w-4">
                  <path d="M3.5 18.5 11.1 5.2a1 1 0 0 1 1.8 0l2.2 3.9-5.4 9.4H3.5Z" />
                  <path d="m13.9 12.4 3.5 6.1h-7l3.5-6.1Z" />
                </svg>
              </div>
              <span className="text-sm uppercase tracking-widest">ACME STORE</span>
            </Link>


<div className="pt-[40px] ml-[20px] :hover-text-grey-400 cursor-pointer">
            <Link href={'#'}> <p>Shipping</p></Link>
            <Link href={'#'}><p>Returns</p></Link>
</div>




<div className="mt-[40px] h8 ml-auto mr-[20px]  ">
<svg 
  viewBox="0 0 24 24"
  aria-hidden="true"
  className="h-6 w-6"
  fill="currentColor"
>
  <path d="M12 .5C5.73.5.5 5.73.5 12c0 5.08 3.29 9.39 7.86 10.91.58.11.79-.25.79-.56 0-.28-.01-1.02-.01-2-3.2.7-3.88-1.54-3.88-1.54-.53-1.33-1.28-1.69-1.28-1.69-1.05-.72.08-.71.08-.71 1.16.08 1.77 1.19 1.77 1.19 1.03 1.76 2.71 1.25 3.37.96.1-.75.4-1.25.73-1.54-2.55-.29-5.23-1.28-5.23-5.7 0-1.26.45-2.29 1.19-3.1-.12-.29-.52-1.47.11-3.06 0 0 .97-.31 3.18 1.18a11.1 11.1 0 0 1 2.9-.39c.98 0 1.97.13 2.9.39 2.2-1.49 3.17-1.18 3.17-1.18.63 1.59.23 2.77.11 3.06.74.81 1.19 1.84 1.19 3.1 0 4.43-2.69 5.41-5.25 5.69.41.36.78 1.08.78 2.18 0 1.57-.01 2.84-.01 3.22 0 .31.21.68.8.56A10.99 10.99 0 0 0 23.5 12C23.5 5.73 18.27.5 12 .5Z" />
</svg>
</div>


        </footer>
        
        
        
        </body>
    </html>
  );
}
