import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
// import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Acme Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {


  // const[serched , setSerched] = useState("")
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
              <header className="border-b-[0.2px] border-gray-500 bg-black p-4">
        <nav className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-6">
            <Link href="/" className="flex items-center gap-2 font-bold text-white">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg border border-gray-200 bg-gray-100 p-2">
                <svg viewBox="0 0 24 24" fill="black" className="h-4 w-4">
                  <path d="M3.5 18.5 11.1 5.2a1 1 0 0 1 1.8 0l2.2 3.9-5.4 9.4H3.5Z" />
                  <path d="m13.9 12.4 3.5 6.1h-7l3.5-6.1Z" />
                </svg>
              </div>
              <span className="text-sm uppercase tracking-widest">ACME STORE</span>
            </Link>

            <div className="flex items-center gap-4 text-sm font-medium text-gray-400">
              <Link href="/bags" className="hover:border-b hover:text-white">Bags</Link>
              <Link href="/shoes" className="hover:border-b hover:text-white">Shoes</Link>
              <Link href="/shopAll" className="hover:border-b hover:text-white">ShopAll</Link>
              <Link href="/sunglasses" className="hover:border-b hover:text-white">Sunglasses</Link>
            </div>
          </div>

          <div className="relative w-80">
            <input
              type="text"
              placeholder="Search for products..."
              className="w-full rounded-lg border border-gray-500 bg-transparent px-4 py-2 pr-10 text-sm text-white focus:border-gray-400 focus:outline-none"
              // value={serched}
              // onChange={(e) => setSerched(e.target.value)}

            />
            <div className="absolute right-0 top-0 flex h-full items-center pr-3">
             <button >
                <svg
                  aria-hidden="true"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className="h-4 w-4 text-gray-500"
                >
                  <circle cx="11" cy="11" r="8" />
                  <path d="m21 21-4.3-4.3" />
                </svg>
              </button>
            </div>
          </div>

          <Link
            href="/cart"
            aria-label="Shopping cart"
            className="relative flex h-11 w-11 items-center justify-center rounded-md border border-gray-500 text-white"
          >
            <svg
              aria-hidden="true"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="h-4 w-4"
            >
              <circle cx="8" cy="21" r="1" />
              <circle cx="19" cy="21" r="1" />
              <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
            </svg>
            <span className="absolute right-1 top-1 flex h-4 w-4 items-center justify-center rounded-full bg-blue-600 text-[10px] font-bold text-white">
              0
            </span>
          </Link>
        </nav>
      </header>
        
        
        
        
        {children}</body>
    </html>
  );
}
